In [17]:
import pandas as pd

parts_df = pd.read_csv("./data/parts_manual_labels_v1.csv")

In [18]:
parts_df

,Call,Parts,P1,P2,P3,P4,P5,Notes
0,N01i,3.0,BB,Tonal up,"Tonal, Peak than flat",NaN,NaN,NaN
1,N01ii,3.0,unclear,unclear,"Tonal, Peak than flat",NaN,NaN,"p1 and p2 much shorter than N01i,"
2,N01iii,3.0,BB,unclear (BB?),"Tonal, Peak than flat",NaN,NaN,"Compared to N01i, p2 has SBI measure"
3,N01iv,3.0,unclear,unclear,"Tonal, Peak slow descending",NaN,NaN,NaN
4,N01v,3.0,BB,"Tonal, squigle","Tonal, Peak than flat",NaN,NaN,NaN
5,N02,3.0,"Tonal, tight","Tonal, squigle","Tonal, sharp rise",NaN,NaN,seems to have biphonation in high freqs
6,N03,3.0,BB,Gap,"Tonal, descending",NaN,NaN,p2 has sbi measurements but seems like a gap
7,N04,2.0,"Tonal, Peak than flat, upsweep at end","Tonal, tight, short",NaN,NaN,NaN,NaN
8,N05i,2.0,"Tonal, Rise than flat","Tonal, short",NaN,NaN,NaN,NaN
9,N05ii,4.0,"Tonal, Rising","BB, short","Peak, short","BB, short",NaN,NaN
10,N07i,2.0,BB,"Tonal, Rising than flat",NaN,NaN,NaN,NaN
11,N07ii,3.0,BB,"Tonal, Rising than flat","Tonal, Rising than flat, SBI Increasing",NaN,NaN,NaN
12,N07iii,3.0,BB,"Tonal, Rising than flat","Tonal, Rising than flat, SBI Increasing",NaN,NaN,"Very similar to N07ii, jsut different parameters"
13,N07iv,3.0,BB,"Tonal, Rising than flat","Tonal, Rising than flat, SBI Increasing",NaN,NaN,"Very similar to N07ii, jsut different parameters"
14,N08i,2.0,BB,"Tonal, Sharp rise slow descending",NaN,NaN,NaN,NaN
15,N08ii,2.0,BB,"Tonal, tight, short",NaN,NaN,NaN,NaN
16,N08iii,2.0,BB,"Tonal, Peak than flat",NaN,NaN,NaN,NaN
17,N08iv,3.0,BB,Peak,BB,NaN,NaN,NaN
18,N09i,4.0,BB,"Tonal, Rising, short","Tonal, flat","Tonal, Sharp rise, short",NaN,NaN
19,N10,4.0,BB,"Tonal, unclear","Tonal, Rise than descending",BB,NaN,NaN
20,N11i,3.0,"Tonal, tight","BB, long","Tonal, unclear",NaN,NaN,"Tires squeaking one, gaps in between parts"
21,N11ii,3.0,Tonal,"BB, repeating short","Tonal, flat than rise",NaN,NaN,Not present in online catalgoue
22,N12,3.0,"BB, short","Tonal, tihgt","Tonal, rise, SBI increasing",NaN,NaN,NaN
23,N13,4.0,BB,"Tonal, rising",Tonal squigle,"Tonal, tight, short",NaN,NaN
24,N16i,4.0,"Tonal, rising slow, than rise fast",BB,"Tonal, rising, few bands","Tonal, tight, short",NaN,NaN
25,N16ii,4.0,"Tonal, rising slow, than rise fast, short gap ...",tonal,"Tonal, rising, few bands","Tonal, tight, short",NaN,NaN
26,N16ii,4.0,"Tonal, rising slow, than rise fast, short gap ...",tonal,"Tonal, rising, few bands","Tonal, tight, short",NaN,NaN
27,N16iv,3.0,"Tonal, rising slow, than rise fast, short gap ...","Tonal, rising, few bands","Tonal, tight, short",NaN,NaN,the P2 of the other N16s is removed
28,N17,4.0,BB,"Tonal, rise than descending","Tonal, rising","BB, short",NaN,P2 and P3 hard to describe
29,N18,4.0,"Tonal, Rise than flat","BB, short",Peak,"BB, short",NaN,NaN
30,N19,1.0,"Tonal, Peak, flat, Peak",NaN,NaN,NaN,NaN,"2 Peaks,"
31,N20,1.0,"Tonal, Peak",NaN,NaN,NaN,NaN,NaN
32,N21,3.0,BB,"Tonal, Peak",BB,NaN,NaN,NaN
33,N23i,2.0,"Tonal, Flat, Wide","Tonal, U than flat, downsweep",NaN,NaN,NaN,P2 could have been separate in 2 or 3 parts imo
34,N23ii,2.0,"Tonal, Flat, Wide","Tonal, Flat than downsweep",NaN,NaN,NaN,P2 could have been 2 parts
35,N24,3.0,"Tonal, Flat","Tonal, Rise than flat","Tonal, tight, descending",NaN,NaN,NaN
36,N25,4.0,"Tonal, Tight, Rise,","Tonal, descending, wide","Tonal, U, short","Tonal, tight, descending than flat",NaN,"We have examples of these found in our data, (..."
37,N26,4.0,"BB, unclear","Tonal, flat, tight","Tonal, peak","BB, unclear",NaN,No good examples in the online catalogue
38,N27,2.0,BB,"Tonal, Rise flat descending",NaN,NaN,NaN,No good examples in the online catalogue
39,N28,2.0,"Tonal, Rising peak, than flat, wide",U,NaN,NaN,NaN,NaN
40,N29,3.0,"Tonal flat, wide",U,Peak,NaN,NaN,Looks similar to N28
41,N30,2.0,"Tonal rising, wide","Tonal, up down up down up down",NaN,NaN,NaN,quite a unique call
42,N32i,2.0,"tonal rising, SBI increasing, biphonation","tonal, peak, short",NaN,NaN,NaN,NaN
43,N32ii,3.0,"Tonal, flat than upsweep","tonal, rising than flat wide",sharp raise tonal,NaN,NaN,Online catalogue example starts with a BB section
44,N33,4.0,BB,"Tonal ,peak flat peak, squigle","tonal, rising, SBI increasing",unclear,NaN,NaN
45,N34,3.0,"BB, long","Tonal, upsweep, flat, downsweep","Tonal, rising, tight",NaN,NaN,p2 has wider SBI than p3
46,N35,5.0,BB short,Tonal tight flat,Tonal wide,NaN,NaN,NaN
47,N38,NaN,NaN,NaN,NaN,NaN,NaN,No examples in online catalogue
48,N39,2.0,"tonal, flat downsweep, then gap","tonal, rising",NaN,NaN,NaN,online looks different than paper
49,N40,1.0,BB,NaN,NaN,NaN,NaN,BB but sounds almost like a parrot
50,N41,4.0,"BB, gap","BB short, gap","Tonal, very tight, rising, gap",tonal flat,NaN,Most gap structure in a call
51,N42,3.0,BB,"Tonal, upsweep flat downsweep","Tonal, squiggle, peak slow descending",NaN,NaN,P3 could be subdivided in 2 parts
52,N43,1.0,"Tonal, upsweep flat, biphonation",NaN,NaN,NaN,NaN,NaN
53,N44,3.0,BB,"Tonal, Peak, flat,","Tonal, downsweep than flat, tight",NaN,NaN,NaN
54,N45,1.0,"Tonal, flat / very melow U shape",NaN,NaN,NaN,NaN,NaN
55,N46,2.0,"Tonal, tight descending,",BB,NaN,NaN,NaN,"in online spects, seem to have a gap between 2..."
56,N47,2.0,BB,"Tonal, rising squiggle",NaN,NaN,NaN,very similar to N2 (couldn't tell the difference)
57,N48,3.0,tonal flat,"tonal, U",mix of BB and tonal peak,NaN,NaN,weird mix for P3
58,N50,1.0,"Upsweep, flat, Tonal",NaN,NaN,NaN,NaN,"Paper only notes on part, but spects and image..."
59,N51,1.0,"tonal tight rising, peak, increase SBI",NaN,NaN,NaN,NaN,NaN

In [12]:
parts_df["Parts"].value_counts()

Parts
3.0    23
2.0    15
4.0    13
1.0     7
5.0     1
Name: count, dtype: int64

In [19]:
# Get all unique part descriptions from P1-P5 columns
all_parts = []

# Iterate through P1-P5 columns
for col in ['P1', 'P2', 'P3', 'P4', 'P5']:
    # Get all non-null values from this column
    values = parts_df[col].dropna()
    
    # Split by comma and collect all parts
    for val in values:
        if pd.notna(val) and str(val).strip():  # Check if value exists
            # Split by comma
            parts = [p.strip() for p in str(val).split(',')]
            all_parts.extend(parts)

# Get unique values (case-sensitive) and sort
unique_parts = sorted(set(all_parts))

print(f"Total unique part descriptions: {len(unique_parts)}\n")
print("Unique part descriptions:")
print("-" * 50)
for part in unique_parts:
    print(f"  - {part}")

Total unique part descriptions: 82

Unique part descriptions:
--------------------------------------------------
  -
  - BB
  - BB short
  - Flat
  - Flat than downsweep
  - Gap
  - Peak
  - Peak  slow descending
  - Peak than flat
  - Rise
  - Rise flat descending
  - Rise than descending
  - Rise than flat
  - Rising
  - Rising peak
  - Rising than flat
  - SBI Increasing
  - SBI increasing
  - Sharp rise
  - Sharp rise slow descending
  - Tight
  - Tonal
  - Tonal flat
  - Tonal rising
  - Tonal squigle
  - Tonal tight flat
  - Tonal up
  - Tonal wide
  - U
  - U than flat
  - Upsweep
  - Wide
  - biphonation
  - descending
  - descending than flat
  - downsweep
  - downsweep than flat
  - few bands
  - flat
  - flat / very melow U shape
  - flat downsweep
  - flat than rise
  - flat than upsweep
  - gap
  - increase SBI
  - long
  - mix of BB and tonal peak
  - peak
  - peak flat peak
  - peak slow descending
  - repeating short
  - rise
  - rise than descending
  - rising
  - rising slow
  - rising squiggle
  - rising than flat wide
  - sharp raise tonal
  - sharp rise
  - short
  - short gap after
  - squiggle
  - squigle
  - than flat
  - than rise fast
  - then gap
  - tight
  - tight descending
  - tihgt
  - tonal
  - tonal flat
  - tonal rising
  - tonal tight rising
  - unclear
  - unclear (BB?)
  - up down up down up down
  - upsweep
  - upsweep at end
  - upsweep flat
  - upsweep flat downsweep
  - very tight
  - wide

Missing: N11i
Missing: N11ii
Missing: N19
Missing: N24
Missing: N35
Missing: N38

In [24]:
online_catalogue_df = pd.read_csv("./data/ford-catalogue/online_catalogue.csv")
online_catalogue_df.head()

,call_type,clan,pod,sample,audio_file,image_file,population,description_file,filename,audio_file_path,audio_url,audio_filename,relative_path,catalog_population,catalog_site_details,gcs_audio_path,gcs_path,audio_fp,spect_fp
0,N01i,A,A1,1,Northern Resident/media/A_clan/N01i-A1-1.mp3,Northern Resident/media/A_clan/N01i-A1-1.webp,Northern Resident,Northern Resident/call-type-description/call-t...,N01i-A1-1,Northern Resident/media/A_clan/N01i-A1-1.mp3,https://orca-dev.research.sfu.ca/johnf/multi3/...,N01i-A1-1.mp3,Northern Resident/media/A_clan/N01i-A1-1.mp3,['Northern Resident'],"{'catalogue': {'is_root': 'true', 'title': ""Ex...",gs://esp-data-ingestion/ford-catalogue/Norther...,gs://esp-data-ingestion/ford-catalogue/Norther...,data/ford-catalogue/Northern Resident/media/A_...,data/ford-catalogue/spects/N01i-A1-1.png
1,N01i,A,A1,2,Northern Resident/media/A_clan/N01i-A1-2.mp3,Northern Resident/media/A_clan/N01i-A1-2.webp,Northern Resident,Northern Resident/call-type-description/call-t...,N01i-A1-2,Northern Resident/media/A_clan/N01i-A1-2.mp3,https://orca-dev.research.sfu.ca/johnf/multi3/...,N01i-A1-2.mp3,Northern Resident/media/A_clan/N01i-A1-2.mp3,['Northern Resident'],"{'catalogue': {'is_root': 'true', 'title': ""Ex...",gs://esp-data-ingestion/ford-catalogue/Norther...,gs://esp-data-ingestion/ford-catalogue/Norther...,data/ford-catalogue/Northern Resident/media/A_...,data/ford-catalogue/spects/N01i-A1-2.png
2,N01i,A,A1,3,Northern Resident/media/A_clan/N01i-A1-3.mp3,Northern Resident/media/A_clan/N01i-A1-3.webp,Northern Resident,Northern Resident/call-type-description/call-t...,N01i-A1-3,Northern Resident/media/A_clan/N01i-A1-3.mp3,https://orca-dev.research.sfu.ca/johnf/multi3/...,N01i-A1-3.mp3,Northern Resident/media/A_clan/N01i-A1-3.mp3,['Northern Resident'],"{'catalogue': {'is_root': 'true', 'title': ""Ex...",gs://esp-data-ingestion/ford-catalogue/Norther...,gs://esp-data-ingestion/ford-catalogue/Norther...,data/ford-catalogue/Northern Resident/media/A_...,data/ford-catalogue/spects/N01i-A1-3.png
3,N01i,A,A1,4,Northern Resident/media/A_clan/N01i-A1-4.mp3,Northern Resident/media/A_clan/N01i-A1-4.webp,Northern Resident,Northern Resident/call-type-description/call-t...,N01i-A1-4,Northern Resident/media/A_clan/N01i-A1-4.mp3,https://orca-dev.research.sfu.ca/johnf/multi3/...,N01i-A1-4.mp3,Northern Resident/media/A_clan/N01i-A1-4.mp3,['Northern Resident'],"{'catalogue': {'is_root': 'true', 'title': ""Ex...",gs://esp-data-ingestion/ford-catalogue/Norther...,gs://esp-data-ingestion/ford-catalogue/Norther...,data/ford-catalogue/Northern Resident/media/A_...,data/ford-catalogue/spects/N01i-A1-4.png
4,N01ii,A,B1,1,Northern Resident/media/A_clan/N01ii-B1-1.mp3,Northern Resident/media/A_clan/N01ii-B1-1.webp,Northern Resident,Northern Resident/call-type-description/call-t...,N01ii-B1-1,Northern Resident/media/A_clan/N01ii-B1-1.mp3,https://orca-dev.research.sfu.ca/johnf/multi3/...,N01ii-B1-1.mp3,Northern Resident/media/A_clan/N01ii-B1-1.mp3,['Northern Resident'],"{'catalogue': {'is_root': 'true', 'title': ""Ex...",gs://esp-data-ingestion/ford-catalogue/Norther...,gs://esp-data-ingestion/ford-catalogue/Norther...,data/ford-catalogue/Northern Resident/media/A_...,data/ford-catalogue/spects/N01ii-B1-1.png

In [25]:
# Add online catalogue info to parts_df
n_examples = []
clans_list = []
pods_list = []

for call in parts_df['Call']:
    # Filter matching rows
    matching_rows = online_catalogue_df[online_catalogue_df['call_type'] == call]
    
    # Count examples
    n_examples.append(len(matching_rows))
    
    # Get unique clans (comma-separated)
    unique_clans = matching_rows['clan'].dropna().unique()
    clans_list.append(', '.join(sorted(unique_clans)) if len(unique_clans) > 0 else '')
    
    # Get unique pods (comma-separated)
    unique_pods = matching_rows['pod'].dropna().unique()
    pods_list.append(', '.join(sorted(unique_pods)) if len(unique_pods) > 0 else '')

# Add columns to parts_df
parts_df['n_online_examples'] = n_examples
parts_df['clans'] = clans_list
parts_df['pods'] = pods_list

parts_df.head()

,Call,Parts,P1,P2,P3,P4,P5,Notes,n_online_examples,clans,pods
0,N01i,3.0,BB,Tonal up,"Tonal, Peak than flat",NaN,NaN,NaN,4,A,A1
1,N01ii,3.0,unclear,unclear,"Tonal, Peak than flat",NaN,NaN,"p1 and p2 much shorter than N01i,",4,A,"B1, I1,I2,I18, I2"
2,N01iii,3.0,BB,unclear (BB?),"Tonal, Peak than flat",NaN,NaN,"Compared to N01i, p2 has SBI measure",2,A,"C1, D1"
3,N01iv,3.0,unclear,unclear,"Tonal, Peak slow descending",NaN,NaN,NaN,1,A,H1
4,N01v,3.0,BB,"Tonal, squigle","Tonal, Peak than flat",NaN,NaN,NaN,1,A,A4

In [26]:
parts_df.to_csv("./data/parts_manual_labels_v2.csv", index=False)

# V3

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
parts_v3 = pd.read_csv("./data/parts_manual_labels_v3.csv")
# parts_v3 = parts_v3[parts_v3["checked_v3"] == True]

parts_v3.reset_index(drop=True, inplace=True)

In [2]:
parts_v3

,Call,Parts,P1,P2,P3,P4,P5,Notes,n_online_examples,clans,pods,P1_old,P1_type,P1_desc,P1_length,P1_always_present,P1_strong_variation,P2_old,P2_type,P2_desc,P2_length,P2_always_present,P2_strong_variation,P3_old,P3_type,P3_desc,P3_length,P3_always_present,P3_strong_variation,P4_old,P4_type,P4_desc,P4_length,P4_always_present,P4_strong_variation,P5_old,P5_type,P5_desc,P5_length,P5_always_present,P5_strong_variation,old_notes,checked_v3
0,N01i,3.0,BB,Tonal up,"Tonal, Peak than flat",NaN,NaN,NaN,4,A,A1,BB,BB,NaN,undefined,True,False,Tonal up,tonal,ascending fast | flat,short,False,True,"Tonal, Peak than flat",tonal,peak flat peak | peak flat,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,True
1,N01ii,3.0,unclear,unclear,"Tonal, Peak than flat",NaN,NaN,"p1 and p2 much shorter than N01i,",4,A,"B1, I1,I2,I18, I2",unclear,BB,NaN,short,False,False,unclear,tonal,ascending fast | gap,short,False,False,"Tonal, Peak than flat",tonal,peak flat,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,"p1 and p2 much shorter than N01i,",True
2,N01iii,3.0,BB,unclear (BB?),"Tonal, Peak than flat",NaN,NaN,"Compared to N01i, p2 has SBI measure",2,A,"C1, D1",BB,BB,NaN,undefined,True,False,unclear (BB?),tonal,flat?,short,False,False,"Tonal, Peak than flat",tonal,peak flat,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,"Compared to N01i, p2 has SBI measure",True
3,N01iv,3.0,unclear,unclear,"Tonal, Peak slow descending",NaN,NaN,NaN,1,A,H1,unclear,NaN,unclear,undefined,True,False,unclear,NaN,unclear,undefined,True,False,"Tonal, Peak slow descending",tonal,peak slow descending,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,False
4,N01v,3.0,BB,"Tonal, squigle","Tonal, Peak than flat",NaN,NaN,NaN,1,A,A4,BB,BB,NaN,undefined,True,False,"Tonal, squigle",tonal,squigle,undefined,True,False,"Tonal, Peak than flat",tonal,peak than flat,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,False
5,N02,3.0,"Tonal, tight","Tonal, squigle","Tonal, sharp rise",NaN,NaN,seems to have biphonation in high freqs,5,A,"A1, A4, A5","Tonal, tight",BB,tight,undefined,False,False,"Tonal, squigle",tonal,squigle,undefined,True,False,"Tonal, sharp rise",tonal,ascending fast,short,False,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,seems to have biphonation in high freqs,True
6,N03,3.0,BB,Gap,"Tonal, descending",NaN,NaN,p2 has sbi measurements but seems like a gap,5,A,"A1, A5, C1, D1",BB,BB,NaN,short,True,False,Gap,gap,NaN,short,False,False,"Tonal, descending",tonal,descending SBI narrowing,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,p2 has sbi measurements but seems like a gap,True
7,N04,2.0,"Tonal, Peak than flat, upsweep at end","Tonal, tight, short",NaN,NaN,NaN,NaN,8,A,"A1, A4, A5","Tonal, Peak than flat, upsweep at end",tonal,"left peak large, flat",undefined,True,False,"Tonal, tight, short",tonal,ascending tight,short,False,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,True
8,N05i,2.0,"Tonal, Rise than flat","Tonal, short",NaN,NaN,NaN,NaN,11,A,"A1, A5, H1, I1,I2,I18","Tonal, Rise than flat",tonal,"upsweep flat | upsweep flat, ascending",undefined,True,True,"Tonal, short",tonal,"tight, ascending",short,False,True,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,True
9,N05ii,4.0,"Tonal, Rising","BB, short","Peak, short","BB, short",NaN,NaN,6,A,"B1, I1,I2,I18, I2","Tonal, Rising",tonal,flat | ascending slow,undefined,True,False,"BB, short",BB,NaN,short,True,False,"Peak, short",tonal,peak,short,False,False,"BB, short",BB,NaN,short,True,False,NaN,NaN,NaN,undefined,True,False,NaN,True
10,N07i,2.0,BB,"Tonal, Rising than flat",NaN,NaN,NaN,EASY,9,A,"A1, A4, A5",BB,BB,NaN,undefined,True,False,"Tonal, Rising than flat",tonal,"upsweep, flat",undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,True
11,N07ii,3.0,BB,"Tonal, Rising than flat","Tonal, Rising than flat, SBI Increasing",NaN,NaN,EASY,2,A,"H1, I1,I2,I18",BB,BB,NaN,undefined,True,False,"Tonal, Rising than flat",tonal,upsweep flat,undefined,True,False,"Tonal, Rising than flat, SBI Increasing",tonal,ascending sbi increasing,undefined,True,True,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,True
12,N07iii,3.0,BB,"Tonal, Rising than flat","Tonal, Rising than flat, SBI Increasing",NaN,NaN,"Very similar to N07ii, jsut different parameters",4,A,"B1, I1,I2,I18",BB,BB,NaN,undefined,True,False,"Tonal, Rising than flat",tonal,upsweep flat,undefined,True,False,"Tonal, Rising than flat, SBI Increasing",tonal,ascending sbi increasing,undefined,True,True,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,"Very similar to N07ii, jsut different parameters",True
13,N07iv,3.0,BB,"Tonal, Rising than flat","Tonal, Rising than flat, SBI Increasing",NaN,NaN,"Very similar to N07ii, jsut different parameters",2,A,"C1, D1",BB,BB,NaN,undefined,True,False,"Tonal, Rising than flat",tonal,upsweep flat,undefined,True,False,"Tonal, Rising than flat, SBI Increasing",tonal,ascending wide,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,"Very similar to N07ii, jsut different parameters",True
14,N08i,2.0,BB,"Tonal, Sharp rise slow descending",NaN,NaN,NaN,spects are hard to read,8,A,"A1, A4, A5, H1",BB,pulsed,NaN,undefined,True,False,"Tonal, Sharp rise slow descending",tonal,left peak,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,True
15,N08ii,2.0,BB,"Tonal, tight, short",NaN,NaN,NaN,NaN,2,A,"C1, D1",BB,pulsed,NaN,undefined,True,False,"Tonal, tight, short",tonal,flat tight,short,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,True
16,N08iii,2.0,BB,"Tonal, Peak than flat",NaN,NaN,NaN,NaN,2,A,"B1, I2",BB,pulsed,NaN,undefined,True,False,"Tonal, Peak than flat",tonal,"peak, flat | descending",undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,True
17,N08iv,3.0,BB,Peak,BB,NaN,NaN,NaN,2,A,"B1, I1,I2,I18",BB,pulsed,NaN,undefined,True,False,Peak,tonal,small peak,short,True,False,BB,BB,NaN,undefined,False,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,True
18,N09i,4.0,BB,"Tonal, Rising, short","Tonal, flat","Tonal, Sharp rise, short",NaN,NaN,4,A,A1,BB,BB,NaN,undefined,True,False,"Tonal, Rising, short",tonal,ascending fast,short,False,False,"Tonal, flat",tonal,flat | ascending slow,undefined,True,False,"Tonal, Sharp rise, short",tonal,ascending fast (tick),short,False,False,NaN,NaN,NaN,undefined,True,False,NaN,True
19,N10,4.0,BB,"Tonal, unclear","Tonal, Rise than descending",BB,NaN,NaN,1,A,A1,BB,BB,NaN,undefined,True,False,"Tonal, unclear",tonal,?,short,False,False,"Tonal, Rise than descending",tonal,"large peak, flat",undefined,True,False,BB,BB,?,short,False,False,NaN,NaN,NaN,undefined,True,False,NaN,True
20,N11i,3.0,"Tonal, tight","BB, long","Tonal, unclear",NaN,NaN,"Tires squeaking one, gaps in between parts",0,NaN,NaN,"Tonal, tight",tonal,tight,undefined,True,False,"BB, long",BB,long,undefined,True,False,"Tonal, unclear",tonal,unclear,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,"Tires squeaking one, gaps in between parts",False
21,N11ii,3.0,Tonal,"BB, repeating short","Tonal, flat than rise",NaN,NaN,Not present in online catalgoue,0,NaN,NaN,Tonal,tonal,NaN,undefined,True,False,"BB, repeating short",BB,repeating short,undefined,True,False,"Tonal, flat than rise",tonal,flat than rise,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,Not present in online catalgoue,False
22,N12,3.0,"BB, short","Tonal, tihgt","Tonal, rise, SBI increasing",NaN,NaN,NaN,13,A,"A1, A4, A5, B1, C1, D1, H1, I1,I2,I18","BB, short",BB,NaN,short,False,False,"Tonal, tihgt",tonal,flat tight,undefined,True,False,"Tonal, rise, SBI increasing",tonal,"ascending sbi increasing | ascending, flat",undefined,False,True,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,True
23,N13,4.0,BB,"Tonal, rising",Tonal squigle,"Tonal, tight, short",NaN,Big variation,3,A,"A1, A5",BB,BB,NaN,undefined,False,False,"Tonal, rising",tonal,ascending,short,False,False,Tonal squigle,tonal,squigle | peak peak,undefined,True,False,"Tonal, tight, short",BB,NaN,short,False,True,NaN,NaN,NaN,undefined,True,False,NaN,True
24,N16i,4.0,"Tonal, rising slow, than rise fast",BB,"Tonal, rising, few bands","Tonal, tight, short",NaN,NaN,3,A,"B1, C1","Tonal, rising slow, than rise fast",tonal,"ascending slow, ascending fast",undefined,True,False,BB,BB,NaN,short,True,False,"Tonal, rising, few bands",tonal,ascending wide| large right peak wide,undefined,False,True,"Tonal, tight, short",BB,NaN,short,False,False,NaN,NaN,NaN,undefined,True,False,NaN,True
25,N16ii,4.0,"Tonal, rising slow, than rise fast, short gap ...",tonal,"Tonal, rising, few bands","Tonal, tight, short",NaN,NaN,4,A,"C1, D1","Tonal, rising slow, than rise fast, short gap ...",tonal,"ascending | flat, ascending",undefined,True,True,tonal,tonal,tight,short,True,False,"Tonal, rising, few bands",tonal,ascending wide | large rigth peak wide,undefined,True,True,"Tonal, tight, short",tonal,tight,short,False,False,NaN,NaN,NaN,undefined,True,False,NaN,True
26,N16iii,4.0,"Tonal, rising slow, than rise fast, short gap ...",tonal,"Tonal, rising, few bands","Tonal, tight, short",NaN,NaN,4,A,"C1, D1","Tonal, rising slow, than rise fast, short gap ...",tonal,"peak, flat, ascending",undefined,True,False,tonal,tonal,NaN,undefined,True,False,"Tonal, rising, few bands",tonal,ascending wide,undefined,True,False,"Tonal, tight, short",tonal,tight,short,False,False,NaN,NaN,NaN,undefined,True,False,NaN,True
27,N16iv,3.0,"Tonal, rising slow, than rise fast, short gap ...","Tonal, rising, few bands","Tonal, tight, short",NaN,NaN,the P2 of the other N16s is removed,2,A,"I1,I2,I18, I2","Tonal, rising slow, than rise fast, short gap ...",tonal,flat | ascending slow,undefined,True,False,"Tonal, rising, few bands",tonal,ascending wide,undefined,True,False,"Tonal, tight, short",BB,tight,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,the P2 of the other N16s is removed,True
28,N17,4.0,BB,"Tonal, rise than descending","Tonal, rising","BB, short",NaN,P2 and P3 hard to describe,3,A,A5,BB,BB,NaN,undefined,True,False,"Tonal, rise than descending",tonal,rise than descending,undefined,True,False,"Tonal, rising",tonal,rising,undefined,True,False,"BB, short",BB,short,undefined,True,False,NaN,NaN,NaN,undefined,True,False,P2 and P3 hard to describe,False
29,N18,4.0,"Tonal, Rise than flat","BB, short",Peak,"BB, short",NaN,NaN,3,A,"B1, C1","Tonal, Rise than flat",tonal,flat,undefined,True,False,"BB, short",BB,NaN,short,True,False,Peak,tonal,peak,short,True,False,"BB, short",BB,NaN,short,True,False,NaN,NaN,NaN,undefined,True,False,NaN,True
30,N19,1.0,"Tonal, Peak, flat, Peak",NaN,NaN,NaN,NaN,"2 Peaks,",0,NaN,NaN,"Tonal, Peak, flat, Peak",tonal,"peak, flat, peak",undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,"2 Peaks,",False
31,N20,1.0,"Tonal, Peak",NaN,NaN,NaN,NaN,single wide peak,4,A,"B1, C1, D1","Tonal, Peak",tonal,peak large,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,True
32,N21,3.0,BB,"Tonal, Peak",BB,NaN,NaN,NaN,1,A,B1,BB,BB,NaN,short,True,False,"Tonal, Peak",tonal,peak,undefined,True,False,BB,BB,BB | single tone,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,True
33,N23i,2.0,"Tonal, Flat, Wide","Tonal, U than flat, downsweep",NaN,NaN,NaN,P2 could have been separate in 2 or 3 parts imo,4,G,"I11, I31","Tonal, Flat, Wide",tonal,"flat, wide",undefined,True,False,"Tonal, U than flat, downsweep",tonal,"u than flat, downsweep",undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,P2 could have been separate in 2 or 3 parts imo,False
34,N23ii,2.0,"Tonal, Flat, Wide","Tonal, Flat than downsweep",NaN,NaN,NaN,P2 could have been 2 parts,6,G,G1,"Tonal, Flat, Wide",tonal,flat wide,undefined,True,False,"Tonal, Flat than downsweep",tonal,downsweep flat downsweep,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,P2 could have been 2 parts,True
35,N24,3.0,"Tonal, Flat","Tonal, Rise than flat","Tonal, tight, descending",NaN,NaN,NaN,0,NaN,NaN,"Tonal, Flat",tonal,flat,undefined,True,False,"Tonal, Rise than flat",tonal,rise than flat,undefined,True,False,"Tonal, tight, descending",tonal,"tight, descending",undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,False
36,N25,4.0,"Tonal, Tight, Rise,","Tonal, descending, wide","Tonal, U, short","Tonal, tight, descending than flat",NaN,"We have examples of these found in our data, (...",4,G,"G1, I11","Tonal, Tight, Rise,",tonal,tight asending,undefined,True,False,"Tonal, descending, wide",tonal,descending wide & biphonation,undefined,True,False,"Tonal, U, short",tonal,dip,short,True,False,"Tonal, tight, descending than flat",tonal,tight flat | peak,undefined,True,True,NaN,NaN,NaN,undefined,True,False,"We have examples of these found in our data, (...",True
37,N26,4.0,"BB, unclear","Tonal, flat, tight","Tonal, peak","BB, unclear",NaN,No good examples in the online catalogue,2,G,I11,"BB, unclear",BB,unclear,undefined,True,False,"Tonal, flat, tight",tonal,"flat, tight",undefined,True,False,"Tonal, peak",tonal,peak,undefined,True,False,"BB, unclear",BB,unclear,undefined,True,False,NaN,NaN,NaN,undefined,True,False,No good examples in the online catalogue,False
38,N27,2.0,BB,"Tonal, Rise flat descending",NaN,NaN,NaN,No good examples in the online catalogue,1,A,A1,BB,BB,NaN,undefined,True,False,"Tonal, Rise flat descending",tonal,rise flat descending,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,No good examples in the online catalogue,False
39,N28,2.0,"Tonal, Rising peak, than flat, wide",U,NaN,NaN,NaN,NaN,2,G,G1,"Tonal, Rising peak, than flat, wide",tonal,"rising peak, than flat, wide",undefined,True,False,U,NaN,u,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,False
40,N29,3.0,"Tonal flat, wide",U,Peak,NaN,NaN,Looks similar to N28,2,G,G1,"Tonal flat, wide",tonal,"flat, wide",undefined,True,False,U,NaN,u,undefined,True,False,Peak,NaN,peak,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,Looks similar to N28,False
41,N30,2.0,"Tonal rising, wide","Tonal, up down up down up down",NaN,NaN,NaN,quite a unique call,4,G,"G1, I11, I31","Tonal rising, wide",tonal,"rising, wide",undefined,True,False,"Tonal, up down up down up down",tonal,up down up down up down,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,quite a unique call,False
42,N32i,2.0,"tonal rising, SBI increasing, biphonation","tonal, peak, short",NaN,NaN,NaN,NaN,2,R,R1,"tonal rising, SBI increasing, biphonation",tonal,"ascending sbi increasing, biphonation",undefined,True,False,"tonal, peak, short",tonal,peak,short,False,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,True
43,N32ii,3.0,"Tonal, flat than upsweep","tonal, rising than flat wide",sharp raise tonal,NaN,NaN,Online catalogue example starts with a BB section,1,R,R1,"Tonal, flat than upsweep",tonal,flat than upsweep,undefined,True,False,"tonal, rising than flat wide",tonal,rising than flat wide,undefined,True,False,sharp raise tonal,tonal,sharp raise tonal,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,Online catalogue example starts with a BB section,False
44,N33,4.0,BB,"Tonal ,peak flat peak, squigle","tonal, rising, SBI increasing",unclear,NaN,NaN,2,R,R1,BB,BB,NaN,undefined,True,False,"Tonal ,peak flat peak, squigle",tonal,"peak flat peak, squigle",undefined,True,False,"tonal, rising, SBI increasing",tonal,"rising, sbi increasing",undefined,True,False,unclear,NaN,unclear,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,False
45,N34,3.0,"BB, long","Tonal, upsweep, flat, downsweep","Tonal, rising, tight",NaN,NaN,p2 has wider SBI than p3,2,R,R1,"BB, long",BB,long,undefined,True,False,"Tonal, upsweep, flat, downsweep",tonal,"upsweep, flat, downsweep",undefined,True,False,"Tonal, rising, tight",tonal,"rising, tight",undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,p2 has wider SBI than p3,False
46,N35,5.0,BB short,Tonal tight flat,Tonal wide,NaN,NaN,NaN,0,NaN,NaN,BB short,BB,short,undefined,True,False,Tonal tight flat,tonal,tight flat,undefined,True,False,Tonal wide,tonal,wide,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,False
47,N38,NaN,NaN,NaN,NaN,NaN,NaN,No examples in online catalogue,0,NaN,NaN,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,No examples in online catalogue,False
48,N39,2.0,"tonal, flat downsweep, then gap","tonal, rising",NaN,NaN,NaN,online looks different than paper,2,G,I11,"tonal, flat downsweep, then gap",tonal,"flat downsweep, then gap",undefined,True,False,"tonal, rising",tonal,rising,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,online looks different than paper,False
49,N40,1.0,BB,NaN,NaN,NaN,NaN,BB but sounds almost like a parrot,3,G,"G1, I11",BB,BB,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,BB but sounds almost like a parrot,False
50,N41,4.0,"BB, gap","BB short, gap","Tonal, very tight, rising, gap",tonal flat,NaN,Most gap structure in a call,6,G,"G1, I11, I31","BB, gap",BB,gap,undefined,True,False,"BB short, gap",BB,"short, gap",undefined,True,False,"Tonal, very tight, rising, gap",tonal,"very tight, rising, gap",undefined,True,False,tonal flat,tonal,flat,undefined,True,False,NaN,NaN,NaN,undefined,True,False,Most gap structure in a call,False
51,N42,3.0,BB,"Tonal, upsweep flat downsweep","Tonal, squiggle, peak slow descending",NaN,NaN,P3 could be subdivided in 2 parts,1,R,R1,BB,BB,NaN,undefined,True,False,"Tonal, upsweep flat downsweep",tonal,upsweep flat downsweep,undefined,True,False,"Tonal, squiggle, peak slow descending",tonal,"squiggle, peak slow descending",undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,P3 could be subdivided in 2 parts,False
52,N43,1.0,"Tonal, upsweep flat, biphonation",NaN,NaN,NaN,NaN,NaN,2,R,R1,"Tonal, upsweep flat, biphonation",tonal,"upsweep flat, biphonation",undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,False
53,N44,3.0,BB,"Tonal, Peak, flat,","Tonal, downsweep than flat, tight",NaN,NaN,NaN,3,G,G1,BB,BB,NaN,undefined,True,False,"Tonal, Peak, flat,",tonal,"peak, flat,",undefined,True,False,"Tonal, downsweep than flat, tight",tonal,"downsweep than flat, tight",undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,NaN,NaN,undefined,True,False,NaN,False

In [108]:
# Get all unique part descriptions from P1-P5 columns
all_parts = []

# Iterate through P1-P5 columns
for col in ['P1_desc', 'P2_desc', 'P3_desc', 'P4_desc', 'P5_desc']:
    # Get all non-null values from this column
    values = parts_v3[col].dropna()
    
    # Split by comma and collect all parts
    for val in values:
        if pd.notna(val) and str(val).strip():  # Check if value exists
            # Split by comma or |
            segs = []
            for chunk in str(val).split(','):
                segs.extend([p.strip() for p in chunk.split('|')])
            all_parts.extend([p for p in segs if p])

# Get unique values (case-sensitive) and sort
unique_parts = sorted(set(all_parts))

print(f"Total unique part descriptions: {len(unique_parts)}\n")
print("Unique part descriptions:")
print("-" * 50)
for part in unique_parts:
    print(f"  - {part}")

Total unique part descriptions: 74

Unique part descriptions:
--------------------------------------------------
  - ?
  - BB
  - ascending
  - ascending fast
  - ascending fast (tick)
  - ascending sbi increasing
  - ascending slow
  - ascending tight
  - ascending wide
  - biphonation
  - descending
  - descending SBI narrowing
  - descending wide & biphonation
  - dip
  - downsweep
  - downsweep flat downsweep
  - downsweep than flat
  - flat
  - flat / very melow u shape
  - flat downsweep
  - flat than rise
  - flat than upsweep
  - flat tight
  - flat wide
  - flat?
  - gap
  - increase sbi
  - large peak
  - large right peak wide
  - large rigth peak wide
  - left peak
  - left peak large
  - long
  - mix of bb and tonal peak
  - peak
  - peak  slow descending
  - peak flat
  - peak flat peak
  - peak large
  - peak peak
  - peak slow descending
  - peak than flat
  - repeating short
  - rise flat descending
  - rise than descending
  - rise than flat
  - rising
  - rising peak
  - rising squiggle
  - rising than flat wide
  - sbi increasing
  - sharp raise tonal
  - short
  - single tone
  - small peak
  - squiggle
  - squigle
  - than flat
  - then gap
  - tight
  - tight asending
  - tight descending
  - tight flat
  - tight rising
  - tonal
  - u
  - u than flat
  - unclear
  - up down up down up down
  - upsweep
  - upsweep flat
  - upsweep flat downsweep
  - very tight
  - wide

In [10]:
import re
match_dict = {
    "single tone" : "SINGLE_TONE",
    "sbi increasing" : "SBI_INC",

    "sbi decreasing" : "SBI_DEC",
    "sbi narrowing" : "SBI_DEC",
    "tight" : "SBI_TIGHT",
    "wide" : "SBI_WIDE",
    "ascending" : "ASC",
    "descending" : "DESC",
    "upsweep" : "UPSWEEP",
    "downsweep" : "DOWNSWEEP",
    "squiggle" : "SQUIGGLE",
    "squigle" : "SQUIGGLE",
    "fast" : "FAST",
    "slow" : "SLOW",
    "peak" : "PEAK",
    "flat" : "FLAT",
    "biphonation" : "BIPHO",
    ",": ",",
    "|" : "|",
    "gap" : "GAP",
    "asending" : "ASC",
    "left" : "LEFT",
    "right" : "RIGHT",
    "dip" : "DIP",
    "large" : "LARGE",
    "small" : "SMALL",
    "rigth" : "RIGHT",
    "?" : "?",
    "flat?" : "FLAT ?",
    
    
    
}

parts_v3["P1_tokens"] = ""
parts_v3["P2_tokens"] = ""
parts_v3["P3_tokens"] = ""
parts_v3["P4_tokens"] = ""
parts_v3["P5_tokens"] = ""
parts_v3["tokens_string"] = ""

for i, call in parts_v3.iterrows():
    print(call["Call"])
    print(i)
    if call["checked_v3"] == False:
        print("skipping")
        continue

    main_string = ""

    token_string = ""
    for j in range(1, int(call["Parts"]) +1):
        
        part_desc = call[f"P{j}_desc"]
        part_type = call[f"P{j}_type"]
        part_length = "." + call[f"P{j}_length"] if call[f"P{j}_length"] != "undefined" else ""
        part_always_present = "!" if call[f"P{j}_always_present"] else ""
        part_variation = "~" if call[f"P{j}_strong_variation"] else ""
        
        if pd.notna(part_desc) and str(part_desc).strip():

            main_string += f"[{part_type}{part_length}{part_always_present}{part_variation}] {part_desc} "

        part_type = call[f"P{j}_type"]
        
        type_token = part_type.upper() if part_type.lower() != "tonal" else ""

        part_length = call[f"P{j}_length"] 
      
        length_token = part_length.upper() if part_length != "undefined" else ""

        # Tokenize the description
        part_desc = call[f"P{j}_desc"]
        desc_lower = str(part_desc).lower() if pd.notna(part_desc) else ""
        original_desc = desc_lower  # Keep original for comparison

        # Track matched positions
        matched_positions = set()

        # Sort by length (longest first) to match multi-word phrases first
        sorted_patterns = sorted(match_dict.items(), key=lambda x: len(x[0]), reverse=True)

        # Find all occurrences
        matches = []  # List of (position, pattern, token)
        for pattern, token in sorted_patterns:
            start = 0
            while True:
                pos = desc_lower.find(pattern, start)
                if pos == -1:
                    break
                # Check if this position overlaps with already matched text
                pattern_positions = set(range(pos, pos + len(pattern)))
                if not pattern_positions.intersection(matched_positions):
                    matches.append((pos, pattern, token))
                    matched_positions.update(pattern_positions)
                start = pos + 1

        # Sort matches by position to preserve order
        matches.sort(key=lambda x: x[0])
        desc_tokens = [match[2] for match in matches]

        # Build matched string for comparison
        desc_token_string = " ".join(desc_tokens) if desc_tokens else ""

        # Find unmatched text
        unmatched_chars = []
        for char_idx, char in enumerate(original_desc):
            if char_idx not in matched_positions:
                unmatched_chars.append(char)

        unmatched_text = ''.join(unmatched_chars).strip()
        # Clean up extra spaces and commas
        unmatched_text = ' '.join(unmatched_text.split())
        unmatched_text = unmatched_text.replace(' , ', ', ').strip(' ,')

        # print(f"P{j} original: {part_desc}")
        # print(f"P{j} tokens: {desc_token_string}")
        if unmatched_text:
            print(f"P{j} unmatched: {unmatched_text}")
        
        part_token_string = f"{type_token} {length_token} {desc_token_string}"
        part_token_string = part_token_string.rstrip()

        parts_v3.at[i, f"P{j}_tokens"] = part_token_string

        token_string += f"({part_token_string}) "
  
    # Remove any spaces after '(' or before ')' using regex
    token_string_clean = re.sub(r'\(\s+', '(', token_string)
    token_string_clean = re.sub(r'\s+\)', ')', token_string_clean)
    parts_v3.at[i, "tokens_string"] = token_string_clean

        
    print(main_string)
    print(token_string_clean)

N01i
0
[tonal.short~] ascending fast | flat [tonal!] peak flat peak | peak flat
(BB) (SHORT ASC FAST | FLAT) (PEAK FLAT PEAK | PEAK FLAT)
N01ii
1
[tonal.short] ascending fast | gap [tonal!] peak flat
(BB SHORT) (SHORT ASC FAST | GAP) (PEAK FLAT)
N01iii
2
[tonal.short] flat? [tonal!] peak flat
(BB) (SHORT FLAT ?) (PEAK FLAT)
N01iv
3
skipping
N01v
4
skipping
N02
5
[BB] tight [tonal!] squigle [tonal.short] ascending fast
(BB  SBI_TIGHT) (SQUIGGLE) (SHORT ASC FAST)
N03
6
[tonal!] descending SBI narrowing
(BB SHORT) (GAP SHORT) (DESC SBI_DEC)
N04
7
[tonal!] left peak large, flat [tonal.short] ascending tight
(LEFT PEAK LARGE , FLAT) (SHORT ASC SBI_TIGHT)
N05i
8
[tonal!~] upsweep flat | upsweep flat, ascending [tonal.short~] tight, ascending
(UPSWEEP FLAT | UPSWEEP FLAT , ASC) (SHORT SBI_TIGHT , ASC)
N05ii
9
[tonal!] flat | ascending slow [tonal.short] peak
(FLAT | ASC SLOW) (BB SHORT) (SHORT PEAK) (BB SHORT)
N07i
10
[tonal!] upsweep, flat
(BB) (UPSWEEP , FLAT)
N07ii
11
[tonal!] upsweep flat [tonal!~] ascending sbi increasing
(BB) (UPSWEEP FLAT) (ASC SBI_INC)
N07iii
12
[tonal!] upsweep flat [tonal!~] ascending sbi increasing
(BB) (UPSWEEP FLAT) (ASC SBI_INC)
N07iv
13
[tonal!] upsweep flat [tonal!] ascending wide
(BB) (UPSWEEP FLAT) (ASC SBI_WIDE)
N08i
14
[tonal!] left peak
(PULSED) (LEFT PEAK)
N08ii
15
[tonal.short!] flat tight
(PULSED) (SHORT FLAT SBI_TIGHT)
N08iii
16
[tonal!] peak, flat | descending
(PULSED) (PEAK , FLAT | DESC)
N08iv
17
[tonal.short!] small peak
(PULSED) (SHORT SMALL PEAK) (BB)
N09i
18
P4 unmatched: (tick)
[tonal.short] ascending fast [tonal!] flat | ascending slow [tonal.short] ascending fast (tick)
(BB) (SHORT ASC FAST) (FLAT | ASC SLOW) (SHORT ASC FAST)
N10
19
[tonal.short] ? [tonal!] large peak, flat [BB.short] ?
(BB) (SHORT ?) (LARGE PEAK , FLAT) (BB SHORT ?)
N11i
20
skipping
N11ii
21
skipping
N12
22
[tonal!] flat tight [tonal~] ascending sbi increasing | ascending, flat
(BB SHORT) (FLAT SBI_TIGHT) (ASC SBI_INC | ASC , FLAT)
N13
23
[tonal.short] ascending [tonal!] squigle | peak peak
(BB) (SHORT ASC) (SQUIGGLE | PEAK PEAK) (BB SHORT)
N16i
24
[tonal!] ascending slow, ascending fast [tonal~] ascending wide| large right peak wide
(ASC SLOW , ASC FAST) (BB SHORT) (ASC SBI_WIDE | LARGE RIGHT PEAK SBI_WIDE) (BB SHORT)
N16ii
25
[tonal!~] ascending | flat, ascending [tonal.short!] tight [tonal!~] ascending wide | large rigth peak wide [tonal.short] tight
(ASC | FLAT , ASC) (SHORT SBI_TIGHT) (ASC SBI_WIDE | LARGE RIGHT PEAK SBI_WIDE) (SHORT SBI_TIGHT)
N16iii
26
[tonal!] peak, flat, ascending [tonal!] ascending wide [tonal.short] tight
(PEAK , FLAT , ASC) () (ASC SBI_WIDE) (SHORT SBI_TIGHT)
N16iv
27
[tonal!] flat | ascending slow [tonal!] ascending wide [BB!] tight
(FLAT | ASC SLOW) (ASC SBI_WIDE) (BB  SBI_TIGHT)
N17
28
skipping
N18
29
[tonal!] flat [tonal.short!] peak
(FLAT) (BB SHORT) (SHORT PEAK) (BB SHORT)
N19
30
skipping
N20
31
[tonal!] peak large
(PEAK LARGE)
N21
32
P3 unmatched: bb
[tonal!] peak [BB!] BB | single tone
(BB SHORT) (PEAK) (BB  | SINGLE_TONE)
N23i
33
skipping
N23ii
34
[tonal!] flat wide [tonal!]  downsweep flat downsweep
(FLAT SBI_WIDE) (DOWNSWEEP FLAT DOWNSWEEP)
N24
35
skipping
N25
36
P2 unmatched: &
[tonal!] tight asending [tonal!] descending wide & biphonation [tonal.short!] dip [tonal!~] tight flat | peak
(SBI_TIGHT ASC) (DESC SBI_WIDE BIPHO) (SHORT DIP) (SBI_TIGHT FLAT | PEAK)
N26
37
skipping
N27
38
skipping
N28
39
skipping
N29
40
skipping
N30
41
skipping
N32i
42
[tonal!] ascending sbi increasing, biphonation [tonal.short] peak
(ASC SBI_INC , BIPHO) (SHORT PEAK)
N32ii
43
skipping
N33
44
skipping
N34
45
skipping
N35
46
skipping
N38
47
skipping
N39
48
skipping
N40
49
skipping
N41
50
skipping
N42
51
skipping
N43
52
skipping
N44
53
skipping
N45
54
skipping
N46
55
skipping
N47
56
skipping
N48
57
skipping
N50
58
skipping
N51
59
skipping

In [8]:
parts_v3[["P1_desc", "P1_tokens", "P2_desc", "P2_tokens", "P3_desc", "P3_tokens", "P4_desc", "P4_tokens", "P5_desc", "P5_tokens"]]

,P1_desc,P1_tokens,P2_desc,P2_tokens,P3_desc,P3_tokens,P4_desc,P4_tokens,P5_desc,P5_tokens
0,NaN,BB,ascending fast | flat,SHORT ASC FAST | FLAT,peak flat peak | peak flat,PEAK FLAT PEAK | PEAK FLAT,NaN,,NaN,
1,NaN,BB SHORT,ascending fast | gap,SHORT ASC FAST | GAP,peak flat,PEAK FLAT,NaN,,NaN,
2,NaN,BB,flat?,SHORT FLAT ?,peak flat,PEAK FLAT,NaN,,NaN,
3,unclear,,unclear,,peak slow descending,,NaN,,NaN,
4,NaN,,squigle,,peak than flat,,NaN,,NaN,
5,tight,BB SBI_TIGHT,squigle,SQUIGGLE,ascending fast,SHORT ASC FAST,NaN,,NaN,
6,NaN,BB SHORT,NaN,GAP SHORT,descending SBI narrowing,DESC SBI_DEC,NaN,,NaN,
7,"left peak large, flat","LEFT PEAK LARGE , FLAT",ascending tight,SHORT ASC SBI_TIGHT,NaN,,NaN,,NaN,
8,"upsweep flat | upsweep flat, ascending","UPSWEEP FLAT | UPSWEEP FLAT , ASC","tight, ascending","SHORT SBI_TIGHT , ASC",NaN,,NaN,,NaN,
9,flat | ascending slow,FLAT | ASC SLOW,NaN,BB SHORT,peak,SHORT PEAK,NaN,BB SHORT,NaN,
10,NaN,BB,"upsweep, flat","UPSWEEP , FLAT",NaN,,NaN,,NaN,
11,NaN,BB,upsweep flat,UPSWEEP FLAT,ascending sbi increasing,ASC SBI_INC,NaN,,NaN,
12,NaN,BB,upsweep flat,UPSWEEP FLAT,ascending sbi increasing,ASC SBI_INC,NaN,,NaN,
13,NaN,BB,upsweep flat,UPSWEEP FLAT,ascending wide,ASC SBI_WIDE,NaN,,NaN,
14,NaN,PULSED,left peak,LEFT PEAK,NaN,,NaN,,NaN,
15,NaN,PULSED,flat tight,SHORT FLAT SBI_TIGHT,NaN,,NaN,,NaN,
16,NaN,PULSED,"peak, flat | descending","PEAK , FLAT | DESC",NaN,,NaN,,NaN,
17,NaN,PULSED,small peak,SHORT SMALL PEAK,NaN,BB,NaN,,NaN,
18,NaN,BB,ascending fast,SHORT ASC FAST,flat | ascending slow,FLAT | ASC SLOW,ascending fast (tick),SHORT ASC FAST,NaN,
19,NaN,BB,?,SHORT ?,"large peak, flat","LARGE PEAK , FLAT",?,BB SHORT ?,NaN,
20,tight,,long,,unclear,,NaN,,NaN,
21,NaN,,repeating short,,flat than rise,,NaN,,NaN,
22,NaN,BB SHORT,flat tight,FLAT SBI_TIGHT,"ascending sbi increasing | ascending, flat","ASC SBI_INC | ASC , FLAT",NaN,,NaN,
23,NaN,BB,ascending,SHORT ASC,squigle | peak peak,SQUIGGLE | PEAK PEAK,NaN,BB SHORT,NaN,
24,"ascending slow, ascending fast","ASC SLOW , ASC FAST",NaN,BB SHORT,ascending wide| large right peak wide,ASC SBI_WIDE | LARGE RIGHT PEAK SBI_WIDE,NaN,BB SHORT,NaN,
25,"ascending | flat, ascending","ASC | FLAT , ASC",tight,SHORT SBI_TIGHT,ascending wide | large rigth peak wide,ASC SBI_WIDE | LARGE RIGHT PEAK SBI_WIDE,tight,SHORT SBI_TIGHT,NaN,
26,"peak, flat, ascending","PEAK , FLAT , ASC",NaN,,ascending wide,ASC SBI_WIDE,tight,SHORT SBI_TIGHT,NaN,
27,flat | ascending slow,FLAT | ASC SLOW,ascending wide,ASC SBI_WIDE,tight,BB SBI_TIGHT,NaN,,NaN,
28,NaN,,rise than descending,,rising,,short,,NaN,
29,flat,FLAT,NaN,BB SHORT,peak,SHORT PEAK,NaN,BB SHORT,NaN,
30,"peak, flat, peak",,NaN,,NaN,,NaN,,NaN,
31,peak large,PEAK LARGE,NaN,,NaN,,NaN,,NaN,
32,NaN,BB SHORT,peak,PEAK,BB | single tone,BB | SINGLE_TONE,NaN,,NaN,
33,"flat, wide",,"u than flat, downsweep",,NaN,,NaN,,NaN,
34,flat wide,FLAT SBI_WIDE,downsweep flat downsweep,DOWNSWEEP FLAT DOWNSWEEP,NaN,,NaN,,NaN,
35,flat,,rise than flat,,"tight, descending",,NaN,,NaN,
36,tight asending,SBI_TIGHT ASC,descending wide & biphonation,DESC SBI_WIDE BIPHO,dip,SHORT DIP,tight flat | peak,SBI_TIGHT FLAT | PEAK,NaN,
37,unclear,,"flat, tight",,peak,,unclear,,NaN,
38,NaN,,rise flat descending,,NaN,,NaN,,NaN,
39,"rising peak, than flat, wide",,u,,NaN,,NaN,,NaN,
40,"flat, wide",,u,,peak,,NaN,,NaN,
41,"rising, wide",,up down up down up down,,NaN,,NaN,,NaN,
42,"ascending sbi increasing, biphonation","ASC SBI_INC , BIPHO",peak,SHORT PEAK,NaN,,NaN,,NaN,
43,flat than upsweep,,rising than flat wide,,sharp raise tonal,,NaN,,NaN,
44,NaN,,"peak flat peak, squigle",,"rising, sbi increasing",,unclear,,NaN,
45,long,,"upsweep, flat, downsweep",,"rising, tight",,NaN,,NaN,
46,short,,tight flat,,wide,,NaN,,NaN,
47,NaN,,NaN,,NaN,,NaN,,NaN,
48,"flat downsweep, then gap",,rising,,NaN,,NaN,,NaN,
49,NaN,,NaN,,NaN,,NaN,,NaN,
50,gap,,"short, gap",,"very tight, rising, gap",,flat,,NaN,
51,NaN,,upsweep flat downsweep,,"squiggle, peak slow descending",,NaN,,NaN,
52,"upsweep flat, biphonation",,NaN,,NaN,,NaN,,NaN,
53,NaN,,"peak, flat,",,"downsweep than flat, tight",,NaN,,NaN,
54,flat / very melow u shape,,NaN,,NaN,,NaN,,NaN,
55,"tight descending,",,NaN,,NaN,,NaN,,NaN,
56,NaN,,rising squiggle,,NaN,,NaN,,NaN,
57,flat,,u,,mix of bb and tonal peak,,NaN,,NaN,
58,"upsweep, flat, tonal",,NaN,,NaN,,NaN,,NaN,
59,"tight rising, peak, increase sbi",,NaN,,NaN,,NaN,,NaN,

In [11]:
parts_v3["checked_v4"] = parts_v3["checked_v3"] 
parts_v3.to_csv("./data/parts_manual_labels_v4.csv", index=False)