In [1]:
import pandas as pd

parts_df = pd.read_csv("./data/parts_manual_labels_v1.csv")

In [4]:
parts_df

,Call,Parts,P1,P2,P3,P4,P5,Notes
0,N01i,3.0,BB,Tonal up,"Tonal, Peak than flat",NaN,NaN,NaN
1,N01ii,3.0,unclear,unclear,"Tonal, Peak than flat",NaN,NaN,"p1 and p2 much shorter than N01i,"
2,N01iii,3.0,BB,unclear (BB?),"Tonal, Peak than flat",NaN,NaN,"Compared to N01i, p2 has SBI measure"
3,N01iv,3.0,unclear,unclear,"Tonal, Peak slow descending",NaN,NaN,NaN
4,N01v,3.0,BB,"Tonal, squigle","Tonal, Peak than flat",NaN,NaN,NaN
5,N02,3.0,"Tonal, tight","Tonal, squigle","Tonal, sharp rise",NaN,NaN,seems to have biphonation in high freqs
6,N03,3.0,BB,Gap,"Tonal, descending",NaN,NaN,p2 has sbi measurements but seems like a gap
7,N04,2.0,"Tonal, Peak than flat, upsweep at end","Tonal, tight, short",NaN,NaN,NaN,NaN
8,N05i,2.0,"Tonal, Rise than flat","Tonal, short",NaN,NaN,NaN,NaN
9,N05ii,4.0,"Tonal, Rising","BB, short","Peak, short","BB, short",NaN,NaN
10,N07i,2.0,BB,"Tonal, Rising than flat",NaN,NaN,NaN,NaN
11,N07ii,3.0,BB,"Tonal, Rising than flat","Tonal, Rising than flat, SBI Increasing",NaN,NaN,NaN
12,N07iii,3.0,BB,"Tonal, Rising than flat","Tonal, Rising than flat, SBI Increasing",NaN,NaN,"Very similar to N07ii, jsut different parameters"
13,N07iv,3.0,BB,"Tonal, Rising than flat","Tonal, Rising than flat, SBI Increasing",NaN,NaN,"Very similar to N07ii, jsut different parameters"
14,N08i,2.0,BB,"Tonal, Sharp rise slow descending",NaN,NaN,NaN,NaN
15,N08ii,2.0,BB,"Tonal, tight, short",NaN,NaN,NaN,NaN
16,N08iii,2.0,BB,"Tonal, Peak than flat",NaN,NaN,NaN,NaN
17,N08iv,3.0,BB,Peak,BB,NaN,NaN,NaN
18,N09i,4.0,BB,"Tonal, Rising, short","Tonal, flat","Tonal, Sharp rise, short",NaN,NaN
19,N10,4.0,BB,"Tonal, unclear","Tonal, Rise than descending",BB,NaN,NaN
20,N11i,3.0,"Tonal, tight","BB, long","Tonal, unclear",NaN,NaN,"Tires squeaking one, gaps in between parts"
21,N11ii,3.0,Tonal,"BB, repeating short","Tonal, flat than rise",NaN,NaN,Not present in online catalgoue
22,N12,3.0,"BB, short","Tonal, tihgt","Tonal, rise, SBI increasing",NaN,NaN,NaN
23,N13,4.0,BB,"Tonal, rising",Tonal squigle,"Tonal, tight, short",NaN,NaN
24,N16i,4.0,"Tonal, rising slow, than rise fast",BB,"Tonal, rising, few bands","Tonal, tight, short",NaN,NaN
25,N16ii,4.0,"Tonal, rising slow, than rise fast, short gap ...",tonal,"Tonal, rising, few bands","Tonal, tight, short",NaN,NaN
26,N16ii,4.0,"Tonal, rising slow, than rise fast, short gap ...",tonal,"Tonal, rising, few bands","Tonal, tight, short",NaN,NaN
27,N16iv,3.0,"Tonal, rising slow, than rise fast, short gap ...","Tonal, rising, few bands","Tonal, tight, short",NaN,NaN,the P2 of the other N16s is removed
28,N17,4.0,BB,"Tonal, rise than descending","Tonal, rising","BB, short",NaN,P2 and P3 hard to describe
29,N18,4.0,"Tonal, Rise than flat","BB, short",Peak,"BB, short",NaN,NaN
30,N19,1.0,"Tonal, Peak, flat, Peak",NaN,NaN,NaN,NaN,"2 Peaks,"
31,N20,1.0,"Tonal, Peak",NaN,NaN,NaN,NaN,NaN
32,N21,3.0,BB,"Tonal, Peak",BB,NaN,NaN,NaN
33,N23i,2.0,"Tonal, Flat, Wide","Tonal, U than flat, downsweep",NaN,NaN,NaN,P2 could have been separate in 2 or 3 parts imo
34,N23ii,2.0,"Tonal, Flat, Wide","Tonal, Flat than downsweep",NaN,NaN,NaN,P2 could have been 2 parts
35,N24,3.0,"Tonal, Flat","Tonal, Rise than flat","Tonal, tight, descending",NaN,NaN,NaN
36,N25,4.0,"Tonal, Tight, Rise,","Tonal, descending, wide","Tonal, U, short","Tonal, tight, descending than flat",NaN,"We have examples of these found in our data, (..."
37,N26,4.0,"BB, unclear","Tonal, flat, tight","Tonal, peak","BB, unclear",NaN,No good examples in the online catalogue
38,N27,2.0,BB,"Tonal, Rise flat descending",NaN,NaN,NaN,No good examples in the online catalogue
39,N28,2.0,"Tonal, Rising peak, than flat, wide",U,NaN,NaN,NaN,NaN
40,N29,3.0,"Tonal flat, wide",U,Peak,NaN,NaN,Looks similar to N28
41,N30,2.0,"Tonal rising, wide","Tonal, up down up down up down",NaN,NaN,NaN,quite a unique call
42,N32i,2.0,"tonal rising, SBI increasing, biphonation","tonal, peak, short",NaN,NaN,NaN,NaN
43,N32ii,3.0,"Tonal, flat than upsweep","tonal, rising than flat wide",sharp raise tonal,NaN,NaN,Online catalogue example starts with a BB section
44,N33,4.0,BB,"Tonal ,peak flat peak, squigle","tonal, rising, SBI increasing",unclear,NaN,NaN
45,N34,3.0,"BB, long","Tonal, upsweep, flat, downsweep","Tonal, rising, tight",NaN,NaN,p2 has wider SBI than p3
46,N35,5.0,BB short,Tonal tight flat,Tonal wide,NaN,NaN,NaN
47,N38,NaN,NaN,NaN,NaN,NaN,NaN,No examples in online catalogue
48,N39,2.0,"tonal, flat downsweep, then gap","tonal, rising",NaN,NaN,NaN,online looks different than paper
49,N40,1.0,BB,NaN,NaN,NaN,NaN,BB but sounds almost like a parrot
50,N41,4.0,"BB, gap","BB short, gap","Tonal, very tight, rising, gap",tonal flat,NaN,Most gap structure in a call
51,N42,3.0,BB,"Tonal, upsweep flat downsweep","Tonal, squiggle, peak slow descending",NaN,NaN,P3 could be subdivided in 2 parts
52,N43,1.0,"Tonal, upsweep flat, biphonation",NaN,NaN,NaN,NaN,NaN
53,N44,3.0,BB,"Tonal, Peak, flat,","Tonal, downsweep than flat, tight",NaN,NaN,NaN
54,N45,1.0,"Tonal, flat / very melow U shape",NaN,NaN,NaN,NaN,NaN
55,N46,2.0,"Tonal, tight descending,",BB,NaN,NaN,NaN,"in online spects, seem to have a gap between 2..."
56,N47,2.0,BB,"Tonal, rising squiggle",NaN,NaN,NaN,very similar to N2 (couldn't tell the difference)
57,N48,3.0,tonal flat,"tonal, U",mix of BB and tonal peak,NaN,NaN,weird mix for P3
58,N50,1.0,"Upsweep, flat, Tonal",NaN,NaN,NaN,NaN,"Paper only notes on part, but spects and image..."
59,N51,1.0,"tonal tight rising, peak, increase SBI",NaN,NaN,NaN,NaN,NaN

In [3]:
import os
from pathlib import Path

# Get the directory with screenshots
image_dir = Path("./data/ford_paper_spects/")

# Get all screenshot files and sort by modification time (oldest first)
screenshot_files = sorted(
    image_dir.glob("*.png"),
    key=lambda x: x.stat().st_mtime
)

print(f"Found {len(screenshot_files)} screenshot files")
print(f"Found {len(parts_df)} calls in parts_df")

# Verify counts match
if len(screenshot_files) == len(parts_df):
    print("\n✓ Counts match! Ready to rename.")
else:
    print(f"\n⚠ Warning: {len(screenshot_files)} files but {len(parts_df)} calls")

Found 59 screenshot files
Found 60 calls in parts_df

⚠ Warning: 59 files but 60 calls

In [ ]:
# Perform the renaming
renamed_count = 0
for i, old_file in enumerate(screenshot_files):
    call_name = parts_df.iloc[i]['Call']
    new_name = f"{call_name}_paper_spect.png"
    new_path = old_file.parent / new_name
    
    # Rename the file
    old_file.rename(new_path)
    renamed_count += 1
    
    # Print progress every 10 files
    if (i + 1) % 10 == 0:
        print(f"Renamed {i + 1}/{len(screenshot_files)} files...")

print(f"\n✓ Successfully renamed {renamed_count} files!")
print("\nSample of renamed files:")
renamed_files = sorted(image_dir.glob("*_paper_spect.png"))[:5]
for f in renamed_files:
    print(f"  - {f.name}")

Renamed 10/60 files...
Renamed 20/60 files...
Renamed 30/60 files...
Renamed 40/60 files...
Renamed 50/60 files...
Renamed 60/60 files...

✓ Successfully renamed 60 files!

Sample of renamed files:

In [4]:
parts_df

,Call,Parts,P1,P2,P3,P4,P5,Notes
0,N1i,3.0,BB,Tonal up,"Tonal, Peak than flat",NaN,NaN,NaN
1,N1ii,3.0,unclear,unclear,"Tonal, Peak than flat",NaN,NaN,"p1 and p2 much shorter than N1i,"
2,N1iii,3.0,BB,unclear (BB?),"Tonal, Peak than flat",NaN,NaN,"Compared to N1i, p2 has SBI measure"
3,N1iv,3.0,unclear,unclear,"Tonal, Peak slow descending",NaN,NaN,NaN
4,N1v,3.0,BB,"Tonal, squigle","Tonal, Peak than flat",NaN,NaN,NaN
5,N2,3.0,"Tonal, tight","Tonal, squigle","Tonal, sharp rise",NaN,NaN,seems to have biphonation in high freqs
6,N3,3.0,BB,Gap,"Tonal, descending",NaN,NaN,p2 has sbi measurements but seems like a gap
7,N4,2.0,"Tonal, Peak than flat, upsweep at end","Tonal, tight, short",NaN,NaN,NaN,NaN
8,N5i,2.0,"Tonal, Rise than flat","Tonal, short",NaN,NaN,NaN,NaN
9,N5ii,4.0,"Tonal, Rising","BB, short","Peak, short","BB, short",NaN,NaN
10,N7i,2.0,BB,"Tonal, Rising than flat",NaN,NaN,NaN,NaN
11,N7ii,3.0,BB,"Tonal, Rising than flat","Tonal, Rising than flat, SBI Increasing",NaN,NaN,NaN
12,N7iii,3.0,BB,"Tonal, Rising than flat","Tonal, Rising than flat, SBI Increasing",NaN,NaN,"Very similar to N7ii, jsut different parameters"
13,N7iv,3.0,BB,"Tonal, Rising than flat","Tonal, Rising than flat, SBI Increasing",NaN,NaN,"Very similar to N7ii, jsut different parameters"
14,N8i,2.0,BB,"Tonal, Sharp rise slow descending",NaN,NaN,NaN,NaN
15,N8ii,2.0,BB,"Tonal, tight, short",NaN,NaN,NaN,NaN
16,N8iii,2.0,BB,"Tonal, Peak than flat",NaN,NaN,NaN,NaN
17,N8iv,3.0,BB,Peak,BB,NaN,NaN,NaN
18,N9i,4.0,BB,"Tonal, Rising, short","Tonal, flat","Tonal, Sharp rise, short",NaN,NaN
19,N10,4.0,BB,"Tonal, unclear","Tonal, Rise than descending",BB,NaN,NaN
20,N11i,3.0,"Tonal, tight","BB, long","Tonal, unclear",NaN,NaN,"Tires squeaking one, gaps in between parts"
21,N11ii,3.0,Tonal,"BB, repeating short","Tonal, flat than rise",NaN,NaN,Not present in online catalgoue
22,N12,3.0,"BB, short","Tonal, tihgt","Tonal, rise, SBI increasing",NaN,NaN,NaN
23,N13,4.0,BB,"Tonal, rising",Tonal squigle,"Tonal, tight, short",NaN,NaN
24,N16i,4.0,"Tonal, rising slow, than rise fast",BB,"Tonal, rising, few bands","Tonal, tight, short",NaN,NaN
25,N16ii,4.0,"Tonal, rising slow, than rise fast, short gap ...",tonal,"Tonal, rising, few bands","Tonal, tight, short",NaN,NaN
26,N16ii,4.0,"Tonal, rising slow, than rise fast, short gap ...",tonal,"Tonal, rising, few bands","Tonal, tight, short",NaN,NaN
27,N16iv,3.0,"Tonal, rising slow, than rise fast, short gap ...","Tonal, rising, few bands","Tonal, tight, short",NaN,NaN,the P2 of the other N16s is removed
28,N17,4.0,BB,"Tonal, rise than descending","Tonal, rising","BB, short",NaN,P2 and P3 hard to describe
29,N18,4.0,"Tonal, Rise than flat","BB, short",Peak,"BB, short",NaN,NaN
30,N19,1.0,"Tonal, Peak, flat, Peak",NaN,NaN,NaN,NaN,"2 Peaks,"
31,N20,1.0,"Tonal, Peak",NaN,NaN,NaN,NaN,NaN
32,N21,3.0,BB,"Tonal, Peak",BB,NaN,NaN,NaN
33,N23i,2.0,"Tonal, Flat, Wide","Tonal, U than flat, downsweep",NaN,NaN,NaN,P2 could have been separate in 2 or 3 parts imo
34,N23ii,2.0,"Tonal, Flat, Wide","Tonal, Flat than downsweep",NaN,NaN,NaN,P2 could have been 2 parts
35,N24,3.0,"Tonal, Flat","Tonal, Rise than flat","Tonal, tight, descending",NaN,NaN,NaN
36,N25,4.0,"Tonal, Tight, Rise,","Tonal, descending, wide","Tonal, U, short","Tonal, tight, descending than flat",NaN,"We have examples of these found in our data, (..."
37,N26,4.0,"BB, unclear","Tonal, flat, tight","Tonal, peak","BB, unclear",NaN,No good examples in the online catalogue
38,N27,2.0,BB,"Tonal, Rise flat descending",NaN,NaN,NaN,No good examples in the online catalogue
39,N28,2.0,"Tonal, Rising peak, than flat, wide",U,NaN,NaN,NaN,NaN
40,N29,3.0,"Tonal flat, wide",U,Peak,NaN,NaN,Looks similar to N28
41,N30,2.0,"Tonal rising, wide","Tonal, up down up down up down",NaN,NaN,NaN,quite a unique call
42,N32i,2.0,"tonal rising, SBI increasing, biphonation","tonal, peak, short",NaN,NaN,NaN,NaN
43,N32ii,3.0,"Tonal, flat than upsweep","tonal, rising than flat wide",sharp raise tonal,NaN,NaN,Online catalogue example starts with a BB section
44,N33,4.0,BB,"Tonal ,peak flat peak, squigle","tonal, rising, SBI increasing",unclear,NaN,NaN
45,N34,3.0,"BB, long","Tonal, upsweep, flat, downsweep","Tonal, rising, tight",NaN,NaN,p2 has wider SBI than p3
46,N35,5.0,BB short,Tonal tight flat,Tonal wide,NaN,NaN,NaN
47,N38,NaN,NaN,NaN,NaN,NaN,NaN,No examples in online catalogue
48,N39,2.0,"tonal, flat downsweep, then gap","tonal, rising",NaN,NaN,NaN,online looks different than paper
49,N40,1.0,BB,NaN,NaN,NaN,NaN,BB but sounds almost like a parrot
50,N41,4.0,"BB, gap","BB short, gap","Tonal, very tight, rising, gap",tonal flat,NaN,Most gap structure in a call
51,N42,3.0,BB,"Tonal, upsweep flat downsweep","Tonal, squiggle, peak slow descending",NaN,NaN,P3 could be subdivided in 2 parts
52,N43,1.0,"Tonal, upsweep flat, biphonation",NaN,NaN,NaN,NaN,NaN
53,N44,3.0,BB,"Tonal, Peak, flat,","Tonal, downsweep than flat, tight",NaN,NaN,NaN
54,N45,1.0,"Tonal, flat / very melow U shape",NaN,NaN,NaN,NaN,NaN
55,N46,2.0,"Tonal, tight descending,",BB,NaN,NaN,NaN,"in online spects, seem to have a gap between 2..."
56,N47,2.0,BB,"Tonal, rising squiggle",NaN,NaN,NaN,very similar to N2 (couldn't tell the difference)
57,N48,3.0,tonal flat,"tonal, U",mix of BB and tonal peak,NaN,NaN,weird mix for P3
58,N50,1.0,"Upsweep, flat, Tonal",NaN,NaN,NaN,NaN,"Paper only notes on part, but spects and image..."
59,N51,1.0,"tonal tight rising, peak, increase SBI",NaN,NaN,NaN,NaN,NaN